# Generated by Django 5.2.1 on 2025-11-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='antecedentes_familiares_texto',
            field=models.TextField(blank=True, help_text='Con quién vive y antecedentes de salud.'),
        ),
        migrations.CreateModel(
            name='InformePIEProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('autor', 'Autor/a'), ('fono', 'Fonoaudiólogo/a'), ('psico', 'Psicólogo/a'), ('tea', 'Educación Diferencial'), ('otra', 'Otro')], default='autor', max_length=10)),
                ('resumen_aporte', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='gestion_pie.informepie')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pie.profesional')),
            ],
            options={
                'ordering': ['creado_en'],
                'unique_together': {('informe', 'profesional')},
            },
        ),
        migrations.CreateModel(
            name='ActividadApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('sesion_ind', 'Sesión individual'), ('sesion_grup', 'Sesión grupal'), ('coord', 'Coordinación/entrevista'), ('eval', 'Evaluación'), ('otra', 'Otra')], max_length=12)),
                ('objetivo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_min', models.PositiveIntegerField(default=45)),
                ('instrumentos', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_pie.profesional')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_pie.informepie')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_pie.informepieprofesional')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
