# Generated by Django 5.2.1 on 2025-11-21 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pie', '0002_alter_anamnesis_antecedentes_familiares_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadapoyo',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_apoyo', to='gestion_pie.informepie'),
        ),
        migrations.CreateModel(
            name='ActividadInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='gestion_pie.informepie')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_pie.profesional')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
