# Generated by Django 5.2.1 on 2025-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pie', '0003_alter_actividadapoyo_informe_actividadinforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informepieprofesional',
            name='rol',
            field=models.CharField(choices=[('autor', 'Autor/a'), ('fono', 'Fonoaudiólogo/a'), ('psico', 'Psicólogo/a'), ('tea', 'Educación Diferencial'), ('otra', 'Otro')], default='autor', max_length=20),
        ),
    ]
